/**
 * SDIS specimen / acquisition contract.
 *
 * Invariant: a specimen can never silently change patient identity. The specimen's
 * patient must match the order item it serves.
 *
 * For future modalities without physical specimens (ECG, EEG, PFT...), the same
 * contract is served by "acquisition" records with kind ACQUISITION.
 */

import type { OrderItemId, PatientId, SpecimenId } from '../../types/ids';

export interface Specimen {
  readonly id: SpecimenId;
  readonly orderItemId: OrderItemId;
  readonly patientId: PatientId;
  readonly kind: SpecimenKind;
  readonly collectedAt: string;
  readonly collectedByRef: string;
  readonly status: SpecimenStatus;
  /**
   * Laboratory accession number (Step 27): a stable OPERATIONAL identity
   * assigned when the specimen is accessioned (RECEIVED). Unique within the
   * owning facility, never recycled, and never a replacement for the global
   * branded entity id. Absent until accessioning.
   */
  readonly accessionNumber?: string;
  /**
   * Explicit exception reason, recorded when the specimen is REJECTED
   * (Step 27). Drawn from the bounded `SpecimenRejectionReason` vocabulary —
   * never free-form clinical judgement. History is preserved: rejection is a
   * status transition, never a deletion.
   */
  readonly rejectionReason?: SpecimenRejectionReason;
  /**
   * Optimistic-concurrency version (LAB-02) — see DiagnosticOrder.version.
   */
  readonly version: number;
}

/**
 * Bounded specimen-exception vocabulary (Step 27). Operational handling
 * reasons only — none of these imply any clinical interpretation of the
 * specimen or the patient (docs/CLINICAL_SAFETY.md).
 */
export type SpecimenRejectionReason =
  | 'INSUFFICIENT_SPECIMEN'
  | 'INCORRECT_SPECIMEN_TYPE'
  | 'DAMAGED_SPECIMEN'
  | 'LABELING_PROBLEM'
  | 'PROCESSING_PROBLEM';

export const SPECIMEN_REJECTION_REASONS: readonly SpecimenRejectionReason[] = [
  'INSUFFICIENT_SPECIMEN',
  'INCORRECT_SPECIMEN_TYPE',
  'DAMAGED_SPECIMEN',
  'LABELING_PROBLEM',
  'PROCESSING_PROBLEM',
] as const;

export function isSpecimenRejectionReason(
  value: unknown,
): value is SpecimenRejectionReason {
  return (
    typeof value === 'string' &&
    (SPECIMEN_REJECTION_REASONS as readonly string[]).includes(value)
  );
}

export type SpecimenKind =
  | 'BLOOD'
  | 'SERUM'
  | 'PLASMA'
  | 'URINE'
  | 'STOOL'
  | 'CSF'
  | 'SWAB'
  | 'TISSUE'
  | 'OTHER'
  | 'ACQUISITION';

export type SpecimenStatus =
  'COLLECTED' | 'RECEIVED' | 'ACCEPTED' | 'REJECTED' | 'PROCESSED';

/**
 * Minimal specimen lifecycle derived from the Step-1 status vocabulary
 * (no extra states, no clinical criteria):
 *
 *   COLLECTED → RECEIVED → ACCEPTED → PROCESSED
 *                        ↘ REJECTED (terminal)
 *
 * The ordering is workflow plumbing only — it encodes no acceptance/rejection
 * criteria, which remain authoritative clinical definitions (REQUIRES
 * AUTHORITATIVE CLINICAL DEFINITION, docs/CLINICAL_SAFETY.md).
 */
export const SPECIMEN_LIFECYCLE: readonly SpecimenStatus[] = [
  'COLLECTED',
  'RECEIVED',
  'ACCEPTED',
  'PROCESSED',
] as const;

const ALLOWED_SPECIMEN_TRANSITIONS: Readonly<
  Record<SpecimenStatus, readonly SpecimenStatus[]>
> = {
  COLLECTED: ['RECEIVED'],
  RECEIVED: ['ACCEPTED', 'REJECTED'],
  ACCEPTED: ['PROCESSED'],
  REJECTED: [],
  PROCESSED: [],
};

export class InvalidSpecimenTransitionError extends Error {
  constructor(from: SpecimenStatus, to: SpecimenStatus) {
    super(`Invalid specimen transition: ${from} → ${to}`);
    this.name = 'InvalidSpecimenTransitionError';
  }
}

export function transitionSpecimenStatus(
  from: SpecimenStatus,
  to: SpecimenStatus,
): SpecimenStatus {
  const allowed = ALLOWED_SPECIMEN_TRANSITIONS[from];
  if (!allowed.includes(to)) {
    throw new InvalidSpecimenTransitionError(from, to);
  }
  return to;
}

/**
 * Accessioning rule (Step 27): an accession number is assigned exactly once,
 * when the specimen is RECEIVED. It is immutable afterwards — re-accessioning
 * or renumbering would break laboratory traceability. The number itself is
 * generated by the application layer; the domain enforces assignment-only-once.
 */
export function assertAccessionAssignment(
  existing: string | undefined,
  next: string | undefined,
): void {
  if (existing !== undefined && next !== undefined && existing !== next) {
    throw new Error(
      'Specimen accession number is already assigned and cannot be changed',
    );
  }
}

/**
 * Accession-number format (Step 27): facility-prefixed, year, and a
 * zero-padded sequence, e.g. `A-2026-000042`. Format-validated at the
 * boundary; uniqueness is enforced by the persistence layer per facility.
 */
export const ACCESSION_PATTERN = /^[A-Z][A-Z0-9]{0,7}-\d{4}-\d{6,8}$/;

/** Guard: specimen and order item must refer to the same patient. */
export function assertSpecimenPatientMatches(
  specimenPatientId: PatientId,
  orderItemPatientId: PatientId,
): void {
  if (specimenPatientId !== orderItemPatientId) {
    throw new Error(
      'Specimen patient does not match the order item patient — identity mismatch',
    );
  }
}
